<?xml version="1.0" ?>
<robot name="tank_model" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find tank_model)/urdf/wheel_gazebo.xacro" />
    <xacro:include filename="$(find tank_model)/urdf/camera_gazebo.xacro"/>

    <xacro:macro name="wheel_joint" params="prefix lr_reflect fb_reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="${lr_reflect*0.1} ${fb_reflect*0.14} -0.05" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <origin xyz=" 0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.4 0.3 0.05" />
            </geometry>
            <material name="yellow">
                <color rgba="1 0.4 0 1"/>
            </material>
        </visual>
    </link>

    <joint name="tank_camera_joint" type="fixed">
        <origin xyz="0.2 0 0.025" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_camera_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <xacro:usb_camera prefix="front_camera"/>


    <joint name="tank_body_joint" type="fixed">
        <origin xyz="-0.05 0 0.025" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="tank_body_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="tank_body_link">
        <visual>
            <origin xyz="0 0 0.025" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>
    </link>

    <joint name="tank_laser_joint" type="fixed">
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <parent link="tank_body_link"/>
        <child link="tank_laser_link"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="tank_laser_link">
        <visual>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1"/>
            </material>
        </visual>
    </link> 
macro
    <xacro:wheel_joint prefix="left_front" lr_reflect="1" fb_reflect="1"/>
    <xacro:wheel prefix="left_front"/>

    <xacro:wheel_joint prefix="left" lr_reflect="1" fb_reflect="-1"/>
    <xacro:wheel prefix="left"/>

    <xacro:wheel_joint prefix="right_front" lr_reflect="-1" fb_reflect="1"/>
    <xacro:wheel prefix="right_front"/>

    <xacro:wheel_joint prefix="right" lr_reflect="-1" fb_reflect="-1"/>
    <xacro:wheel prefix="right"/>

    <gazebo>
        <plugin name="differential_drive_controller" 
                filename="libgazebo_ros_diff_drive.so">                
                <update_rate>30</update_rate>
                <left_joint>left_front_wheel_joint</left_joint>
                <right_joint>right_front_wheel_joint</right_joint>
                <wheel_separation>${wheel_joint_y*2}</wheel_separation>
                <wheel_diameter>${2*wheel_radius}</wheel_diameter>
                <max_wheel_torque>20</max_wheel_torque>
                <max_wheel_acceleration>1.0</max_wheel_acceleration>
                <command_topic>cmd_vel</command_topic>
                <publish_odom>true</publish_odom>
                <publish_odom_tf>true</publish_odom_tf>
                <publish_wheel_tf>true</publish_wheel_tf>
                <odometry_topic>odom</odometry_topic>
                <odometry_frame>odom</odometry_frame>
                <robot_base_frame>base_footprint</robot_base_frame>
                <odometry_source>1</odometry_source>
        </plugin>
    </gazebo> 

</robot>
